### PR TITLE
Refactors out the subprocess.call commands in favor of using the charms.docker helpers

### PR DESCRIPTION
**Pull request by lazypower**

### CODE REVIEW

**Comment by mbruzek** [comment]
@chuckbutler these changes look great, they really clean up the code!  I thought you told me this was a work in progress and not to merge yet.  Once we verify this new code works I would be happy to merge this.

**Comment by lazypower** [comment]
This is ready :) It verified on my test deployment, i encourage you to validate before officially merging.

**Comment by lazypower** [comment]
@mbruzek  dont forget about this one ^_^

**Comment by mbruzek** [comment]
This branch has conflicts and is superceded by PR #21.

**Pull request closed without merging**
